### ISSUE TITLE
SiteMap

### ISSUE THREAD

**Issue by Seff7** [Seff7/Witryna-KALK#1]
Mapa strony w formie drzewka z uwzględnieniem wszystkich podstron.
Deadline: 18.03.2015

**Comment by bigkamcia** [comment]
![site map](https://cloud.githubusercontent.com/assets/11406944/6695597/b7c5b870-cce2-11e4-9585-c404a6adfbbb.png)

**Comment by Seff7** [comment]
Poprawić SiteMap zgodnie z zaleceniami.

**Comment by bigkamcia** [comment]
![site map v2](https://cloud.githubusercontent.com/assets/11406944/6814790/3a1bc3b0-d282-11e4-918a-682c34b0a00c.png)

**Comment by bigkamcia** [comment]
![site map v3](https://cloud.githubusercontent.com/assets/11406944/6935766/95ddbb22-d84a-11e4-8248-563c38dd3540.png)
