### ISSUE TITLE
Założenie serwera

### ISSUE THREAD

**Issue by Seff7** [Seff7/Witryna-KALK#11]
Założenie hostingu dla witryny projektu w celu zdalnego podglądu postępu prac przez członków zespołu projektowego oraz klienta.

Nazwa strony powinna zawierac "kalk".

**Comment by Seff7** [comment]
Hosting założony na portalu friko.pl
Mail: witrynakalk@gmail.com
Postępy pracy nad stroną będzie można obserwować pod adresem: www.kalk.aq.pl
Hasła zostały przekazane każdemu indywidualnie.

**Comment by bigkamcia** [comment]
Hosting założony na portalu friko.pl
Mail: witrynakalk@gmail.com
Postępy pracy nad stroną będzie można obserwować pod adresem: www.kalk.aq.pl
Hasła zostały przekazane każdemu indywidualnie.
