### ISSUE TITLE
Zapoznanie z Wordpressem

### ISSUE THREAD

**Issue by Seff7** [Seff7/Witryna-KALK#13]
Zapoznanie z Wordpressem.

**Comment by asia1992** [comment]
http://webroad.pl/ogloszenia/417-wp-kurs

**Comment by bigkamcia** [comment]
Dobry kurs na youtube:
https://www.youtube.com/watch?v=0nraCpLRiIU
https://www.youtube.com/watch?v=p9rhbfYN0hs
https://www.youtube.com/watch?v=Lxd-S7ABeNk
