### ISSUE TITLE
Przeinstalowanie wordpressa

### ISSUE THREAD

**Issue by Seff7** [Seff7/Witryna-KALK#28]
Do podfolderu w celu umozliwienia zmienienia głownej strony kalk.aq.pl nie będącej szablonem wordpressa

**Comment by bigkamcia** [comment]
Cała Witryna została zainstalowana na nowo. Można rozpoczynać testy nad niezależną Stroną Główną.

**Comment by bigkamcia** [comment]
Nowa Strona Główna działa poprawnie.
