### ISSUE TITLE
Uzupełnić zakładke drużyny

### ISSUE THREAD

**Issue by Seff7** [Seff7/Witryna-KALK#30]
j.w. do 1 czerwca

**Comment by Seff7** [comment]
http://www.kalk-koszalin.com/poddzial,druzyny,21.html itd

**Comment by bigkamcia** [comment]
Drużyny z Dywizji I zostały uzupełnione do końca. W przygotowaniu Dywizja II i III.

**Comment by bigkamcia** [comment]
Drużyny z Dywizji II zostały uzupełnione do końca. W przygotowaniu Dywizja III.

**Comment by bigkamcia** [comment]
Drużyny z Dywizji III zostały uzupełnione do końca.

**Comment by bigkamcia** [comment]
Grafiki przedstawiające Grafiki ogólne dla drużyn zostały wrzucone na serwer.
