### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by Seff7** [Seff7/Witryna-KALK#4]
Który framework będzie najwygodniejszy do stworzenia strony. O co w ogóle w tym chodzi, jak to działa i funkcjonuje. Jakie są zależności i ograniczenia w tworzeniu autorskiej grafiki elementów wyglądu strony i jej uploadu względem dostępnych szablonów. Ponadto jak wygląda kodowanie używając jakiegoś frameworka. Czy można podłączyć do tego napisany html/css lub odwrotnie - czy korzystając z frameworka mozna wyeksportowac kod w postaci tekstowej. Prosze mje tu rozwiać wszelkie wątpliwości i rzucić propozycje wyboru frameworka bądź jego braku.

**Comment by Seff7** [comment]
http://webdesign.ebiznes.org.pl/systemy,cms.htm
http://jakicmswybrac.pl/

**Comment by bigkamcia** [comment]
Moja propozycja frameworka to Wordpress. 
Nie wymaga znajomości php, css, a nawet html, aczkolwiek można ingerować w kod strony. 
Stronę można zbudować, korzystając z gotowych szablonów. 
Jest łatwy w obsłudze, nie wymaga dużo czasu aby się go nauczyć.
